version: '3'

services:
  web:
    build: ./api
    command: /bin/bash -c "rm -f /app/tmp/pids/server.pid && bundle exec rails s -b 0.0.0.0"
    ports:
      - '3003:3000'
    depends_on:
      - db
    volumes:
      - ./api:/app
      - bundle:/usr/local/bundle
    tty: true
    stdin_open: true
  db:
    image: mysql:5.7
    volumes:
      - mysql_data:/var/lib/mysql/
    environment:
      MYSQL_ROOT_PASSWORD: password
    ports:
      - '3403:3306'
  front:
    build: ./front
    volumes:
      - ./front:/app
    ports:
      - '9003:8080'
    tty: true
    stdin_open: true
    command: npm run serve

volumes:
  mysql_data: null
  bundle: null
